### ISSUE TITLE
SSR - Server Side Rendering

### ISSUE THREAD

**Issue by BramDecuypere** [phrase/react-intl-phraseapp#38]
I'm trying to use Phraseapp in my next.js project. But it seems like it is impossible to do since any time I import the package to start using 'FormattedMessage', the app just crashes.

**Comment by FRSgit** [comment]
Hey @BramDecuypere, thank you for reaching us out!
Can you please explain your case more precisely? What is you project configuration? What is the expected outcome? Do you get any error info in the console?

**Comment by BramDecuypere** [comment]
The main problem is that importing this module is looking for window. Which doesn't exist in the node environment.


```
"react": "^16.12.0",
"react-dom": "^16.12.0",
"react-intl": "^3.12.0",
"react-intl-phraseapp": "^1.0.0",
```

```
ReferenceError: window is not defined
(anonymous function)
/Users/bramdecuypere/git/lizy/lizy-fe-2.0/node_modules/react-intl-phraseapp/dist/react-intl-phraseapp.js:1:347
Module._compile
internal/modules/cjs/loader.js:805:30
Module._extensions..js
internal/modules/cjs/loader.js:816:10
Module.load
internal/modules/cjs/loader.js:672:32
tryModuleLoad
internal/modules/cjs/loader.js:612:12
Function.Module._load
internal/modules/cjs/loader.js:604:3
Module.require
internal/modules/cjs/loader.js:711:19
require
internal/modules/cjs/helpers.js:14:16
react-intl-phraseapp
webpack:/external "react-intl-phraseapp":1
> 1 | module.exports = require("react-intl-phraseapp");
View compiled
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
View compiled
Module../src/components/organisms/Hero.tsx
/_next/development/server/static/development/pages/index.js:267:78
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
View compiled
Module../src/pages/index.tsx
/_next/development/server/static/development/pages/index.js:456:84
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
View compiled
3
/_next/development/server/static/development/pages/index.js:621:18
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
```

**Comment by FRSgit** [comment]
@BramDecuypere that's an interesting use-case.
I've just put it on our internal feature board - let us evaluate it and check if (and how) can we support this scenario on our end.
I'll come back to you whenever I have some solid facts to share

**Comment by FRSgit** [comment]
@BramDecuypere Unfortunately this task won't be handled this quarter of the year 😞 

But I'm not sure if I understand your issue completely. `react-intl-phraseapp` is a library for leveraging usage of our [in-context editor](https://help.phrase.com/en/articles/2184890-translate-directly-on-your-website) without need of rewriting your current `react-intl`-managed codebase.

Have you considered enabling `react-intl-phraseapp` **only** for development (or some kind of translation-development) environment with **SSR disabled**?
Also, wouldn't there be a possibility to temporarily feed nodejs global with some dummy, empty window object? Like this: `global.window = {}`. That could temporarily fix the error as well.

And finally, as you said: the fix on our end would be just to not propagate any window-related properties if window object is not available. But the problem is that currently it's the only way we communicate between `react-intl-phraseapp` and `in-context-editor` library itself. So this change would affect at least 5 of our public libraries (and few more of internal) and probably also some of the endusers. It won't be a quick fix for us unfortunately ☹️

**Comment by BramDecuypere** [comment]
@FRSgit Thanks for that update! Yeah, I will try to do one of those suggestions. I just don't like creating yet another environment to make sure our translations team has a place to translate the website in! Because Ideally it would be in staging or something like that. The other one, trying to enable to mock the  ```global.window``` might be a solution to think about, but not sure that is easily accomplished in next.js as well! So maybe I will be forced to have this other environment set-up and do it like that for free on heroku or some similar service. 

We are using the `export` version of Next.js. Just the static building of the website, so I do believe it is hard to turn that off to be honest, since that is how the website is build.

It might be a bit easier with Next than with create-react-app or gatsby. So that is one extra benefit I see right now!

But again, thanks for the update, and the suggested fixes should give any other reader passing by a good idea of how they could potentially solve it.

It's not ideal, but it is what it is. The other benefits I see with Phrase are just too good, to not continue to use it because of this 'technical issue'.
