### ISSUE TITLE
Problem with SSR

### ISSUE THREAD

**Issue by jontelm** [phrase/react-intl-phraseapp#44]
We have been trying to get this working with nextjs.

To fix the SSR problem we had to do some modifications:
functions.ts
https://github.com/bookingbricks/react-intl-phraseapp/pull/1/files#diff-2f64dc1f7fb7525195f073f1b99e7653

webpack.config.js
https://github.com/bookingbricks/react-intl-phraseapp/pull/1/files#diff-11e9f7f953edc64ba14b0cc350ae7b9d

I'm not bad at ts at all so I think someone on your side can create a much better PR for this issues but this seems to be working.

**Comment by FRSgit** [comment]
Hey @jontelm, thanks for the code you've shared! We are already aware of this library missing compatibility with SSR (discussion about this topic is here #38).
While your code seems to overcome the problem I'm not sure now if it's the best solution (you basically disable the `react-intl-phraseapp` always when the app is SSR'ed).

Could you please share with me what's your exact use case? And, if that's possible, it would be great if you could setup some simple project when we can see how exactly you want to use our library and where it fails.

Also, don't worry, your code is quite good 💪The only thing I could point out is that we try not to use the `any` type at all in our codebase. Proper typings help not only us, but also the end users to work with our library. But nevertheless, thanks for the input! I hope that we will be able to solve the problem you've encountered soon! 🚀

**Comment by jontelm** [comment]
Yes maybe not the best solution but a way to make it possible to ssr render the component.
I think it's a fair solution when if it should be server rendered than it's need an extra config on the server side to know if it should enable this lib or not.

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20) and we can take more direct action toward finding a solution.
