### ISSUE TITLE
Problem with nextjs and getInitialProps

### ISSUE THREAD

**Issue by jontelm** [phrase/react-intl-phraseapp#45]
When using this in nextjs we missing props and the solution what we can see is to pass on getInitialProps in injectIntl.tsx

https://github.com/bookingbricks/react-intl-phraseapp/pull/1/files#diff-1930c02bcc32b10c2cb0828da15154feR40

**Comment by FRSgit** [comment]
Hey @jontelm!
Hm, this issue I don't quite understand. Can you please try to give us more description about the issue? What are you trying to achieve and how does our library fail? It would be great if you could provide some failing code example.

We are not working with nextjs on everyday basis, so might need to get some guidance to comprehend the problem you've encountered.

**Comment by jontelm** [comment]
Sems like it's not copy over Static Methods see https://reactjs.org/docs/higher-order-components.html#static-methods-must-be-copied-over

https://github.com/formatjs/react-intl/blob/master/src/components/injectIntl.tsx#L109

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20) and we can take more direct action toward finding a solution.
