### ISSUE TITLE
formatMessage method ignores defaultMessage parameter

### ISSUE THREAD

**Issue by mduecker** [phrase/react-intl-phraseapp#53]
Why does the formatMessage function only consider `id` in messageDescriptor and ignores any other values being passed, like `defaultMessage`?

https://github.com/phrase/react-intl-phraseapp/blob/master/src/injectIntl.tsx#L29
```
        formatMessage(messageDescriptor: { id?: string }): ReturnType<ReactIntlPhraseProps['formatMessage']> {
            const { id } = messageDescriptor;
            if (!id) {
                console.error("formatMessage requires an id")
            } else {
                return this.translate(id);
            }
        }
```

**Comment by theSoenke** [comment]
Hi @mduecker, this package is for integrating the InContext-Editor. It is only intended to add and edit translations from Phrase. The default message will never get used as this package will only display translations from Phrase. This package should not be used in production environments due to these reasons. Does this already clarifies your question a bit?

**Comment by mduecker** [comment]
I don't understand how you would only use this package for dev and not in production?
What I did to add react-intl-phraseapp was to change all my imports of FormattedMessage from
`import {FormattedMessage} from 'react-intl;'` to `import { FormattedMessage } from 'react-intl-phraseapp';`

So now my whole implementation is depending on `react-intl-phraseapp`
I thought the option `phraseEnabled: false` would be used to disable it in production, which makes it fallback to the default react-intl function.

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20) and we can take more direct action toward finding a solution.
