### ISSUE TITLE
Does not work inside other components, like drop down list, buttons, ? operator, just plain use of component works

### ISSUE THREAD

**Issue by franklopez** [phrase/react-intl-phraseapp#55]
We have a project that uses <FormattedMessages> in different ways, and just the ones that are used directly apear translated an connected to phraseapp inline context editor, the other ones the edit icon is there but the content is not linked and the key is shown instead of value.

Ex: 
<button
       type="button"
       className="btn btn-primary btn-multiline"
       onClick={() =>
            executeSomeFunction();
      }
      >
           <i className="rioglyph rioglyph-shopping-cart" />
           <FormattedMessage id="some.translated.key" />
</button>

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20) and we can take more direct action toward finding a solution.
