### ISSUE TITLE
How can I use this module with nextjs (server-side rendering)?

### ISSUE THREAD

**Issue by justinkahrs** [phrase/react-intl-phraseapp#93]
I see a few closed/inactive issues related to SSR issues, but not really any solutions.

Is there a way to get this working? Importing the project gives:

```
ReferenceError: window is not defined
```

Is there a way for this project to check if the window exists before trying to access it? Or is there another (supported) way to integrate the in-context editor?

**Comment by itsahsiao** [comment]
Hey @justinkahrs, we'll have a look into this and get back to you.

**Comment by justinkahrs** [comment]
Hey @itsahsiao any updates on this?

**Comment by itsahsiao** [comment]
@justinkahrs It's on our roadmap and we have it planned to look at this within the next weeks. We'll update you here as soon we have a fix.

**Comment by justinkahrs** [comment]
Thank you!

**Comment by Varpusparvi** [comment]
@justinkahrs Hey! I took a look at this and here is what I found.
- https://github.com/phrase/react-intl-phraseapp/pull/102

Issues I faced when trying this out:
- `createContext` not usable on SSR, and `react-intl` `IntlProvider` using it.
  - Create a wrapper and use it `examples/next-ssr-demo/src/app/server/utils.ts`
- Tree shaking not working with App router on Next, causing import of our whole integration causing again `createContext` problem
  - Import `react-intl-phraseapp/useSSRIntl` instead of `react-intl-phraseapp`
- `self` not being defined on SSR
  - Should be fixed
- `window` not being defined on SSR
  - Should be fixed
- `document` not being defined on SSR
  - Use custom script to import the ICE
  - `examples/next-ssr-demo/src/app/server/page.tsx` adjust your ProjectID and AccountID

I added a demo Next project with SSR instructions you can look at. Hopefully that will be helpful for you. 

Generally you can just make your keys look like `[[__phrase_some.key.id__]]` (or your chosen prefix/suffix) and import the ICE via custom snippet to hopefully make it work in most cases.

https://github.com/formatjs/formatjs/discussions/3977
https://github.com/Shopify/hydrogen/issues/867
https://github.com/vercel/next.js/issues/12557

**Comment by Varpusparvi** [comment]
We have released 4.1.0 for you to try it out, hopefully this will resolve any issues you have with SSR :)

**Comment by justinkahrs** [comment]
@Varpusparvi I pulled in the new version but it seems to be broken

./node_modules/react-intl-phraseapp/dist/react-intl-phraseapp.js
Module build failed: Error: ENOENT: no such file or directory

but it looks like the latest version changed the build output to `index.js` instead of `react-intl-phraseapp.js` I'm not sure where the mismatch might be

**Comment by Varpusparvi** [comment]
@justinkahrs  Fixed in `4.1.2`. Please try it out and get back to us if you still run into any problems. Sorry for the inconvenience!

**Comment by Varpusparvi** [comment]
@MoSattler How are you importing the functions? There is some issue with barrel imports in some cases and I think it might be related. If you can you could try importing specific files and not the whole `react-intl-phraseapp`

> Import react-intl-phraseapp/useSSRIntl instead of react-intl-phraseapp

**Comment by itsahsiao** [comment]
@justinkahrs @MoSattler Are you still facing any issues? Otherwise, we'll be closing this, as we are supporting SSR, specifically with Nextjs, but it should work similarly for Remix. You can refer to the example application in https://github.com/phrase/react-intl-phraseapp/tree/master/examples/next-ssr-demo/src/app/server

**Comment by justinkahrs** [comment]
@itsahsiao I forked the repo and fixed it for my needs and that's what we're using for now until we have some time to revisit the updated versions to see if they addressed the issues I was seeing.

I will close the issue and I can reopen at a later date if I run into more issues trying to implement the updates.

**Comment by itsahsiao** [comment]
@MoSattler Could you let us know what you mean by Phrase is not working? We'd love to look into it, if you could provide us with specific details - it would be great if you could open an issue related to what was not working in your case.

**Comment by itsahsiao** [comment]
@MoSattler We saw [your comment](https://github.com/phrase/react-intl-phraseapp/issues/93#issuecomment-1735171887) and followed up by asking [here](https://github.com/phrase/react-intl-phraseapp/issues/93#issuecomment-1735377140) if you could let us know how you're importing the functions or setting it up. There is also some example code on how to set it up for SSR, which you can find [here in our repo](https://github.com/phrase/react-intl-phraseapp/tree/master/examples/next-ssr-demo/src/app/server), not sure if you had a chance to look at that.

It would be super helpful if you could open a new issue and provide details on your Remix setup, in case the example setup for Nextjs is not applicable, then we can take a better look into it, thanks!

**Comment by justinkahrs** [comment]
Just as a (late) follow-up, I've pulled in your latest changes and can confirm it fixed the issues I was seeing 🙏 Thanks!

**Comment by itsahsiao** [comment]
That's awesome to hear, @justinkahrs! Thank you for letting us know!
